markdown: redcarpet
name: 18F Product Guide
exclude:
- CONTRIBUTING.md
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- go
- vendor

permalink: pretty
highlighter: rouge
incremental: true

sass:
  style: :compressed

# Author/Organization info to be displayed in the templates
author:
  name: 18F
  url: https://18f.gsa.gov

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: /assets/img/18f-logo.png
logoalt: 18F logo

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Introduction
  url: index.html
  internal: true
- text: Welcome to 18F
  url: welcome-to-18f/
  internal: true
- text: Getting Started
  url: getting-started/
  internal: true
- text: What is a Product Lead?
  url: what-is-a-product-lead/
  internal: true
- text: Lifecycle of a Project
  url: lifecycle-of-a-project/
  internal: true
  children:
  - text: Intake
    url: intake/
    internal: true
  - text: Technical evaluations
    url: tech-eval/
    internal: true
  - text: Your team (a.k.a. Staffing)
    url: staffing/
    internal: true
  - text: IAAs & MOUs
    url: iaas-and-mous/
    internal: true
  - text: Budgeting
    url: budgeting/
    internal: true
  - text: Billing
    url: billing/
    internal: true
  - text: Project start
    url: project-start/
    internal: true
  - text: Before You Ship & ATO 
    url: before-you-ship/
    internal: true
  - text: User research
    url: user-research/
    internal: true
  - text: Design and development
    url: design-and-development/
    internal: true
  - text: Infrastructure
    url: infrastructure/
    internal: true
  - text: Project Communications
    url: project-communications/
    internal: true
  - text: After you ship
    url: after-you-ship/
    internal: true
  - text: Renewals & Handoffs
    url: renewals-and-handoffs/
    internal: true
- text: Other Resources
  url: other-resources/
  internal: true


repos:
- name: Product Guide
  description: Main repository
  url: https://github.com/18F/product-guide

back_link:
  url: "https://pages.18f.gov/guides/"
  text: Read more 18F Guides

google_analytics_ua: UA-48605964-19

defaults:
- scope:
    path: ""
  values:
    layout: "guides_style_18f_default"
