markdown: redcarpet
redcarpet:
    renderers: ["link_attributes"]

name: 18F Product Guide
exclude:
- CONTRIBUTING.md
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- go
- vendor

permalink: pretty
highlighter: rouge
incremental: true

sass:
  style: :compressed

# Author/Organization info to be displayed in the templates
author:
  name: 18F Product Chapter
  url: https://18f.gsa.gov

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: /assets/img/18f-logo.png
logoalt: 18F logo

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Welcome
  url: index.html
  internal: true
- text: Discover the current state
  url: discover/
  internal: true
  children:
  - text: Understand the affected users and stakeholders
    url: audience/
    internal: true
  - text: Understand the 'as-is' process
    url: process/
    internal: true
  - text: Undertsand the technical landscape
    url: technical/
    internal: true
  - text: Understand the regulatory landscape
    url: compliance/
    internal: true
- text: Define the future state
  url: future/
  internal: true
  children:
  - text: Define the problem
    url: problem/
    internal: true
  - text: Create the vision
    url: vision/
    internal: true
  - text: Develop a strategy
    url: strategy/
    internal: true
  - text: Craft a roadmap
    url: roadmap/
    internal: true
- text: Deliver the "right way"
  url: deliver/
  internal: true
  children:
  - text: Build a product
    url: build/
    internal: true
  - text: Collaborate and communicate
    url: collaborate/
    internal: true
  - text: Measure success
    url: measure/
    internal: true
- text: Enable partners
  url: partners/
  internal: true
  children:
  - text: Enable partner for long-term success
    url: enable/
    internal: true

repos:
- name: Product Guide
  description: Main repository
  url: https://github.com/18F/product-guide

back_link:
  url: "https://pages.18f.gov/guides/"
  text: Read more 18F Guides

google_analytics_ua: UA-48605964-19

defaults:
- scope:
    path: ""
  values:
    layout: "guides_style_18f_default"

# Configuration for jekyll_pages_api_search plugin gem.
jekyll_pages_api_search:
  # Uncomment this to speed up site generation while developing.
  #skip_index: true

  # Each member of `index_fields` should correspond to a field generated by
  # the jekyll_pages_api. It can hold an optional `boost` member as a signal
  # to Lunr.js to weight the field more highly (default is 1).
  index_fields:
    title:
      boost: 10
    tags:
      boost: 10
    url:
      boost: 5
    body:
